### ISSUE TITLE
meta-issue: restructure module system

### ISSUE THREAD

**Issue by kobbejager** [KIKIRPA/Entropy#31]
- [ ] merge index.php, tools.php and auth.php
- [ ] index.php: basic selection of which modules to show, check general conditions
- [ ] move complex parts of index.php and header.inc.php to init scripts
- [ ] unified module structure: (1) check specific conditions, (2) code/calculations, (3) html
- [ ] header/footer: move code/calculations to index.php (or init scripts), only html template
- [ ] error handling via notification bars
- [ ] modules html structure: (1) html-header, (2) notification bars, (3) main navigation bar, (4) hero/jumbotron and subnav (5) main content and (6) footer
